#!/usr/bin/env python

import os
import sys

import subprocess
import signal


TIMEOUT = 60 * 10

exec_path = '/home/sio4/works/ongsung/ongsung.km/trunk'
exec_name = 'tunneld'


def daemonize():
	"""
	Detach from the terminal and continue as a daemon.
	"""
	# swiped from twisted/scripts/twistd.py
	# See http://www.erlenstar.demon.co.uk/unix/faq_toc.html#TOC16
	# i also swiped it from:
	# http://oebfare.com/blog/2008/nov/03/writing-custom-management-command/
	if os.fork():	# launch child and...
		os._exit(0)	# kill off parent
	os.setsid()
	if os.fork():	# launch child and...
		os._exit(0)	# kill off parent again.
	os.umask(077)
	null = os.open("/dev/null", os.O_RDWR)
	for i in range(3):
		try:
			os.dup2(null, i)
		except OSError, e:
			if e.errno != errno.EBADF:
				raise
	os.close(null)


def sig_alarm(signum,frame):
	global TIMEOUT, proc
	print "sig_alarm: " + "..." + str(proc)
	# set next timeout... signal.alarm(TIMEOUT)

def exit_with_child(child):
	killproc = subprocess.Popen(['kill', str(child.pid)])
	killproc.wait()
	print 'child maybe daed. exit'
	exit()


import httplib, urllib

webhost = 'localhost:8000'

def logger_query(log, prio, serial, uuid):
	params = urllib.urlencode({'statement':log, 'priority':prio,
		'session':uuid, 'serial':serial})
	headers = {"Content-type":"application/x-www-form-urlencoded"}
	conn = httplib.HTTPConnection(webhost)
	conn.request("POST", "/logger/insert/", params, headers)
	response = conn.getresponse()
	data = response.read()
	conn.close()

	return response.status,data.split()[0],data.split()[1]


##############################################################################
#
# main program:

command = '%s/%s %s %s %s %s' % (exec_path, exec_name,
		sys.argv[1], sys.argv[2], sys.argv[3], sys.argv[4])

daemonize()

proc = subprocess.Popen(command.split(),
		stdin=subprocess.PIPE,
		stdout=subprocess.PIPE)

signal.signal(signal.SIGALRM, sig_alarm)
signal.alarm(TIMEOUT)

ret = logger_query("ready to start...", 'L', 0, 'new')
session = ret[1]
serial = 0

while True:
	#proc.stdin.write('username\n')
	#proc.stdin.write('password\n')
	try:
		output = proc.stdout.readline()
	except:
		exit_with_child(proc)
		continue

	if not output:
		break

	if output.find('os_log') != 0:
		continue

	serial += 1

	print "====---- " + output.rstrip()
	logger_query(output.rstrip(), 'L', serial, session)

#proc.communicate()


