#!/usr/bin/env python

import os
import sys


def daemonize():
	"""
	Detach from the terminal and continue as a daemon.
	"""
	# swiped from twisted/scripts/twistd.py
	# See http://www.erlenstar.demon.co.uk/unix/faq_toc.html#TOC16
	# i also swiped it from:
	# http://oebfare.com/blog/2008/nov/03/writing-custom-management-command/
	if os.fork():	# launch child and...
		os._exit(0)	# kill off parent
	os.setsid()
	if os.fork():	# launch child and...
		os._exit(0)	# kill off parent again.
	os.umask(077)
	null = os.open("/dev/null", os.O_RDWR)
	for i in range(3):
		try:
			os.dup2(null, i)
		except OSError, e:
			if e.errno != errno.EBADF:
				raise
	os.close(null)


exec_path = '/home/sio4/works/ongsung/ongsung.km/trunk'
exec_name = 'tunneld.static'

#command = 'xterm -e "%s/%s %s %s %s %s"' % (exec_path, exec_name,
command = '%s/%s %s %s %s %s' % (exec_path, exec_name,
		sys.argv[1], sys.argv[2], sys.argv[3], sys.argv[4])

daemonize()
os.system(command);

